apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: lint-task
spec:
  steps:
    - name: lint
      image: python:3.9
      script: |
        pip install flake8
        flake8 .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test-task
spec:
  steps:
    - name: test
      image: python:3.9
      script: |
        pip install nose
        nosetests

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        echo "Cleaning up temp files..."
        rm -rf /workspace/source/__pycache__
