apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cicd-pipeline
spec:
  tasks:
    - name: test
      taskRef:
        name: test

    - name: build
      taskRef:
        name: build
      runAfter:
        - test

    - name: deploy
      taskRef:
        name: deploy
      runAfter:
        - build
